name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: npm i
      run: |
        echo ">>> PWD"
        pwd
        echo ">>> LS"
        ls
        echo ">>> CD CLIENT && NPM I"
        cd client && npm i

    - name: test
      run: |
        echo "Tests Not Found!"
